#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import Int64MultiArray

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from USART import receive_data, send_upload_command, set_motor_parameter
import threading
import time


class EncoderNode(Node):

    def __init__(self):
        super().__init__('encoder_node')

        self.publisher_ = self.create_publisher(
            Int64MultiArray,
            'wheel_ticks',
            10
        )

        self.get_logger().info("Real encoder node started")

        # Setup serial
        send_upload_command(1)
        time.sleep(0.1)
        set_motor_parameter()
        time.sleep(0.1)

        self.running = True
        threading.Thread(target=self.rx_loop, daemon=True).start()

    def parse_mall(self, msg: str):
