#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import Int64MultiArray

from USART import receive_data, send_upload_command, set_motor_parameter
import threading
import time


class EncoderNode(Node):

    def __init__(self):
        super().__init__('encoder_node')

        self.publisher_ = self.create_publisher(
            Int64MultiArray,
            'wheel_ticks',
            10
        )

        self.get_logger().info("Real encoder node started")

        # Setup serial
        send_upload_command(1)
        time.sleep(0.1)
        set_motor_parameter()
        time.sleep(0.1)

        self.running = True
        threading.Thread(target=self.rx_loop, daemon=True).start()

    def parse_mall(self, msg: str):
        msg = msg.strip()
        if not (msg.startswith("$MAll:") and msg.endswith("#")):
            return None

        payload = msg[len("$MAll:"):-1]
        parts = payload.split(",")

        if len(parts) != 4:
            return None

        return [int(p) for p in parts]

    def rx_loop(self):
        while self.running:
            msg = receive_data()
            if msg:
                ticks = self.parse_mall(msg)
                if ticks is not None:
                    ros_msg = Int64MultiArray()
                    ros_msg.data = ticks
                    self.publisher_.publish(ros_msg)
            time.sleep(0.001)


def main():
    rclpy.init()
    node = EncoderNode()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
