#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import Int64MultiArray
import time


class WheelTicksPublisher(Node):
    def __init__(self):
        super().__init__('wheel_ticks_publisher')
        self.publisher_ = self.create_publisher(
            Int64MultiArray,
            'wheel_ticks',
            10
        )
        self.timer = self.create_timer(0.5, self.publish_ticks)
        self.count = 0
        self.get_logger().info('Wheel ticks publisher started')

    def publish_ticks(self):
        msg = Int64MultiArray()
        msg.data = [self.count, self.count]
        self.publisher_.publish(msg)
        self.get_logger().info(f'Publishing ticks: {msg.data}')
        self.count += 10


def main():
    rclpy.init()
    node = WheelTicksPublisher()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
